{% set version = "0.2.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-spatialwidget
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spatialwidget_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spatialwidget/spatialwidget_{{ version }}.tar.gz
  sha256: 524fdedb810380d6b2cb7a1e761a49c674e415ed3bd0a15d67682d27398f8007

build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-rapidjsonr               # [build_platform != target_platform]
    - r-bh                       # [build_platform != target_platform]
    - r-colourvalues             # [build_platform != target_platform]
    - r-geojsonsf                # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - r-sfheaders                # [build_platform != target_platform]
    - r-jsonify                  # [build_platform != target_platform]
    - r-interleave               # [build_platform != target_platform]
    - r-geometries               # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bh >=1.84.0
    - r-colourvalues >=0.3.9
    - r-geojsonsf >=2.0.3
    - r-geometries >=0.2.4
    - r-interleave >=0.1.2
    - r-jsonify >=1.2.2
    - r-rapidjsonr
    - r-rcpp >=0.12.18
    - r-sfheaders >=0.4.4
  run:
    - r-base
    - r-colourvalues >=0.3.9
    - r-geojsonsf >=2.0.3
    - r-geometries >=0.2.4
    - r-interleave >=0.1.2
    - r-jsonify >=1.2.2
    - r-rapidjsonr
    - r-rcpp >=0.12.18
    - r-sfheaders >=0.4.4

test:
  commands:
    - $R -e "library('spatialwidget')"           # [not win]
    - "\"%R%\" -e \"library('spatialwidget')\""  # [win]

about:
  home: https://symbolixau.github.io/spatialwidget/articles/spatialwidget.html
  dev_url: https://github.com/symbolixau/spatialwidget
  license: GPL-3.0-only
  summary: Many packages use 'htmlwidgets' <https://CRAN.R-project.org/package=htmlwidgets> for interactive plotting of spatial data. This package provides functions for converting R objects, such as simple features, into structures suitable for use in 'htmlwidgets' mapping libraries.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
